Repository earthobservations/wetterdienst, pull requests merged in 2020-09, with the labels that each got.

#135 Update get_nearby_stations
  docs/pages/api.rst
  tests/additionals/test_geo_location.py
  wetterdienst/additionals/geo_location.py
Labels: bug, feature

#141 Bugifx DWDOrigDataColumns names does not match enumeration
  tests/additionals/test_functions.py
  tests/additionals/test_geo_location.py
  wetterdienst/additionals/functions.py
  wetterdienst/additionals/geo_location.py
  wetterdienst/constants/parameter_mapping.py
  wetterdienst/constants/time_resolution_mapping.py
  wetterdienst/enumerations/time_resolution_enumeration.py
Labels: bug

#151 Add "wetterdienst about coverage" to command line interface
  .flake8
  wetterdienst/cli.py
Labels: enhancement

#145 Make the CLI work again
  .flake8
  CHANGELOG.rst
  noxfile.py
  poetry.lock
  pyproject.toml
  tests/test_cli.py
  wetterdienst/additionals/geo_location.py
  wetterdienst/additionals/util.py
  wetterdienst/cli.py
Labels: bug

#166 Compensate compensation for DWD folder anomaly at "hourly/solar" on the parameter level
  wetterdienst/constants/parameter_mapping.py
Labels: enhancement

#158 Emit data to different data sinks and query interactively using SQL
  .coveragerc
  .flake8
  .gitignore
  CHANGELOG.rst
  README.rst
  docs/pages/api.rst
  docs/pages/cli.rst
  docs/pages/development.rst
  docs/pages/installation.rst
  example/sql.py
  noxfile.py
  poetry.lock
  pyproject.toml
  tests/test_cli.py
  tests/test_io.py
  tests/test_run.py
  wetterdienst/__init__.py
  wetterdienst/cli.py
  wetterdienst/io.py
Labels: feature

#114 Add DWD MOSMIX client and parser
  CHANGELOG.rst
  docs/pages/api.rst
  example/mosmix.py
  poetry.lock
  pyproject.toml
  tests/file_path_handling/test_path_handling.py
  tests/test_mosmix.py
  wetterdienst/constants/access_credentials.py
  wetterdienst/file_path_handling/path_handling.py
  wetterdienst/indexing/file_index_creation.py
  wetterdienst/indexing/meta_index_creation.py
  wetterdienst/mosmix.py
Labels: feature

#178 Add basic HTTP API
  .flake8
  CHANGELOG.rst
  docs/index.rst
  docs/pages/installation.rst
  docs/pages/service.rst
  noxfile.py
  poetry.lock
  pyproject.toml
  tests/test_service.py
  wetterdienst/__init__.py
  wetterdienst/cli.py
  wetterdienst/pandas/io.py
  wetterdienst/service.py
Labels: feature
