Repository earthobservations/wetterdienst, pull requests merged in 2022-09, with the labels that each got.

#590 Interpolation
  .github/workflows/install.sh
  CHANGELOG.rst
  CONTRIBUTORS.rst
  README.rst
  THIRD_PARTY_NOTICES
  benchmarks/interpolation.py
  benchmarks/interpolation_over_time.py
  benchmarks/interpolation_precipitation_difference.py
  docs/img/interpolation.png
  docs/usage/python-api.rst
  poetry.lock
  pyproject.toml
  requirements.txt
  tests/core/scalar/test_interpolation.py
  wetterdienst/core/scalar/interpolate.py
  wetterdienst/core/scalar/request.py
  wetterdienst/core/scalar/result.py
  wetterdienst/metadata/columns.py
Labels: enhancement

#735 Tests: Do not strongly depend on `wradlib`
  tests/provider/dwd/radar/test_api_historic.py
  tests/provider/dwd/radar/test_api_latest.py
  tests/provider/dwd/radar/test_api_most_recent.py
Labels: enhancement, tests

#731 Add support for Python 3.11
  .github/workflows/tests.yml
  pyproject.toml
Labels: infrastructure
